# Generated by Django 2.2.5 on 2020-03-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_date'], 'verbose_name_plural': 'myblog'},
        ),
    ]
